# Generated by Django 6.0 on 2025-12-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonial/')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
    ]
